services:
  postgres:
    image: postgres:16-alpine
    container_name: account-ledger-postgres
    environment:
      POSTGRES_DB: account_ledger
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: superpass
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ledger -d account_ledger"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pg-data:
