logging:
  level:
    root: WARN
    com.mohamedali.ledger: INFO
    org.flywaydb: INFO
    com.zaxxer.hikari: INFO
    org.springframework.boot.web.embedded.tomcat: INFO
    org.apache.catalina.core.StandardService: INFO
    org.apache.catalina.core.StandardEngine: INFO
    org.hibernate: OFF
    org.springframework.orm.jpa: OFF
    org.springframework.data.jpa: OFF
    org.springframework.test: WARN
